### ISSUE TITLE
Token alınamıyor.

### ISSUE THREAD

**Issue by ahmetaksoy1985** [BFYDigital/e-arsiv-fatura-dotnet#8]
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by alieymur** [comment]
aynı hatayı bende alıyrum. son bir haftadır.

**Comment by ahmetaksoy1985** [comment]
Çözdüm. Benim repodan kullanabilirsiniz.
https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet
https://github.com/BFYDigital/e-arsiv-fatura-dotnet/issues/7#issuecomment-1518416695

**Comment by alieymur** [comment]
hala token alamıyor

**Comment by ahmetaksoy1985** [comment]
Benim repodan indirip kullanırsanız çalışıyor. Ne hata alıyorsunuz?
https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet

**Comment by Orcunary** [comment]
> Benim repodan indirip kullanırsanız çalışıyor. Ne hata alıyorsunuz? https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet

Ahmet Bey, iyi akşamlar öncelikle ilginiz için teşekkür ederim. Ben sizin projeden kurdum referanslarımı ancak yine token alamadım. Özellikle ` client.DefaultRequestHeaders.Add("user-agent", "Prod");` satırını kontrol ettim ancak yine de token vermedi


`Xunit.Sdk.NotNullException: 'Assert.NotNull() Failure`

**Comment by ahmetaksoy1985** [comment]
Ben console uygulamasından kütüphaneyi kullandım çalıştı. Unit test yazıyorsunuz galiba. XUnit’le ilgili ne olduğunu tam anlayamadım. Denemem lazım. Ayrıca ben kendim özel olarak yazdığım kodlarda da aynı sorunu yaşamıştım. Önce RestClient ile geçici olarak çözdüm. Daha sonra sorunun HttpClient.DefaultRequestHeaders’a user-agent eklenmemesinden olduğunu anladım. Kendi kodlarımı da düzelttim. Hepsi çalışıyor. “Test” yazan kısmı "Prod" olarak değiştirmenize gerek yok. Sadece user-agent gönderilsin diye o şekilde girdim. Önemli olan user-agent gönderilmesi. Başka user-agent da girebilirsiniz. Sonuç olarak Timeout hatası almıyorsunuz.

**Comment by Orcunary** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/110291340/234985256-bf7d3d86-3e6c-4e5d-8f80-fe22016e6997.png">

Aslında Ahmet Bey token aldığını farkettim bir şekilde şu  ekran görüntüsündende anlaşılacağı gibi asenkron Login fonksiyonu nesneden Tokeni geri değer döndürmüyor sanırım neden bilmiyorum ekran görüntüsüne  bir göz atabilme şansınız var mı?


> Ben console uygulamasından kütüphaneyi kullandım çalıştı. Unit test yazıyorsunuz galiba. XUnit’le ilgili ne olduğunu tam anlayamadım. Denemem lazım. Ayrıca ben kendim özel olarak yazdığım kodlarda da aynı sorunu yaşamıştım. Önce RestClient ile geçici olarak çözdüm. Daha sonra sorunun HttpClient.DefaultRequestHeaders’a user-agent eklenmemesinden olduğunu anladım. Kendi kodlarımı da düzelttim. Hepsi çalışıyor. “Test” yazan kısmı "Prod" olarak değiştirmenize gerek yok. Sadece user-agent gönderilsin diye o şekilde girdim. Önemli olan user-agent gönderilmesi. Başka user-agent da girebilirsiniz. Sonuç olarak Timeout hatası almıyorsunuz.

**Comment by ahmetaksoy1985** [comment]
`faturaService.GetToken().Wait();`
Çalışmıştı bende. GetToken, Login komutunu çağırıyor. Token aldıktan sonra başka komutları da çalıştırmıştım. CreateDraftInvoice yapmamıştım sadece Test sunucusuna giriş yapılamadığı için. Şu an deneyemiyorum maalesef. Birkaç gün sonra ancak deneme fırsatım olacak.

**Comment by ahmetaksoy1985** [comment]
Geç oldu kusura bakmayın. Konsol uygulamasından e-arsiv-fatura-dotnet projesini referans olarak tanımladıktan sonra aşağıdaki kodlarla token alıp userdata görüntüleyebiliyorum.  Login fonksiyonu token geri döndürmese diğer fonksiyonlar çalışmaz zaten.

[https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet](url)

![image](https://user-images.githubusercontent.com/11900967/235917971-12792de6-7cfd-4f28-a949-ffc2c2303cf8.png)

`// See https://aka.ms/new-console-template for more information
using BFY.Fatura;
using BFY.Fatura.Configuration;

var configuration = FaturaServiceConfigurationFactory.Create();
configuration.ServiceType = ServiceType.Prod;
configuration.Username = "Kullanıcı Adı";
configuration.Password = "Parola";

FaturaService faturaService = new(configuration);

faturaService.GetToken().Wait();

var userdata = faturaService.GetUserData().GetAwaiter().GetResult();`

**Comment by Orcunary** [comment]
@ahmetaksoy1985 Ahmet Bey merhaba birşey soracaktım size ben anca projeye geri dönebildim, bu defa charset problemiyle karşılaştım. Örneğin fatura nesnesi oluştururken name alanına "Orçun" girdiğimde "OrÃ§un" olarak faturaya taşınıyor
`configuration.Language = "tr";`
olarak ayarlı olsa da sorun nereden kaynaklanıyor bulamadım. 
Rica etsem bir göz atabilir misiniz https://github.com/Orcunary/BFY.Fatura/tree/master/faturaOlustur 
![image](https://github.com/BFYDigital/e-arsiv-fatura-dotnet/assets/110291340/577921d1-43de-422b-b413-539e8018e5a4)

**Comment by ahmetaksoy1985** [comment]
Düzeltebildiniz mi? HttpServices.cs dosyasını değiştirmişsiniz. Ben aktif olarak kullanmıyorum kodları. Benim kendi yazdığım kodlar vardı onları kullanıyorum. Bugün deneyip dönerim size.

**Comment by Orcunary** [comment]
HttpServices.cs Dosyasını düzelttim ama sonuç alamadım maalesef :( Sizi de böyle uğraştırıyorum yardımlarınız için tekrar teşekkürler hocam. Birde e-posta adresinizi alabilir miyim? iletmek istediğim bir konu varda...

**Comment by ahmetaksoy1985** [comment]
Tamam. Ben düzeltirim bugün. Benim daha önceden kendi yazdığım kodlar çalışıyor. Aktif olarak kullanıyorum. Bu kodları tam anlamıyla test etme şansım olmamıştı.

**Comment by ahmetaksoy1985** [comment]
Düzelttim. Json Türkçe karakter olmadan Post etmek gerekiyor. System.Text.Json ile yazmıştım kendi kodlarımı. Otomatik olarak Türkçe karakterleri escapeliyor. Newtonsoft ise Türkçe karakterleri de içeriyor. Bu repo Newtonsoft kullanıyor diye ona uygun olarak kullandım.
`string serialized = JsonConvert.SerializeObject(data, Formatting.Indented, new JsonSerializerSettings() { StringEscapeHandling = StringEscapeHandling.EscapeNonAscii });`

[https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet](https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet)

**Comment by ahmetaksoy1985** [comment]
Mail adresim gmail.
> HttpServices.cs Dosyasını düzelttim ama sonuç alamadım maalesef :( Sizi de böyle uğraştırıyorum yardımlarınız için tekrar teşekkürler hocam. Birde e-posta adresinizi alabilir miyim? iletmek istediğim bir konu varda...

**Comment by Orcunary** [comment]
@ahmetaksoy1985 çok teşekkürler ederim yardımlarınız için 🙏 epostam ulaştı mı size Ahmet Bey

**Comment by ahmetaksoy1985** [comment]
Ulaştı. Çok teşekkür ederim.

**Comment by ahmetaksoy1985** [comment]
GetRecipientDataByTaxIDOrTRID düzelttim. 

[https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet](https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet)

`var configuration = FaturaServiceConfigurationFactory.Create();
configuration.ServiceType = ServiceType.Prod;
configuration.Username = "";
configuration.Password = "";
FaturaService faturaService = new(configuration);
long taxId = long.Parse("");
await faturaService.GetToken();

var response = await faturaService.GetRecipientDataByTaxIDOrTRID(taxId);

if(response is GIBResponseModel<RecipientModel>)
{
    RecipientModel recipient = response.data;
    var unvan = recipient.unvan;
    var adi = recipient.adi;
    var soyadi = recipient.soyadi;
    var vergiDairesi = recipient.vergiDairesi;
}
`

**Comment by Orcunary** [comment]
Ahmet Bey özür dilerim çok başınızı ağrıttım RecipientModel i güncelledim
ama yapamadım bu kod yine hata verdi; neyi yanlış yaptım acaba?

            var configuration = FaturaServiceConfigurationFactory.Create();
            configuration.ServiceType = ServiceType.Prod;
            configuration.Username = "------";
            configuration.Password = "------";
            FaturaService faturaService = new(configuration);
            long taxId = long.Parse(vergikimlik.Text);
            await faturaService.GetToken();

            GIBResponseModel<List<RecipientModel>> response = await
faturaService.GetRecipientDataByTaxIDOrTRID(taxId);

            List<RecipientModel> recipients = response.data;

            foreach (RecipientModel recipient in recipients)
            {

                adi.Text = recipient.adi;
                soyadi.Text = recipient.soyadi;
                unvan.Text = recipient.unvan;
                vergidairesi.Text = recipient.vergiDairesi;

            }



Orçun DİYARBAKIRLI



ahmetaksoy1985 ***@***.***>, 4 Haz 2023 Paz, 19:07 tarihinde
şunu yazdı:

**Comment by ahmetaksoy1985** [comment]
Sizin kodlar çalışmaz. List olmayacak. O yüzden foreach de olmayacak. Benim kodları kullanın. Üstte gönderdim.

**Comment by Orcunary** [comment]
var configuration = FaturaServiceConfigurationFactory.Create();
            configuration.ServiceType = ServiceType.Prod;
            configuration.Username = "-----";
            configuration.Password = "----";
            FaturaService faturaService = new(configuration);
            long taxId = long.Parse(vergikimlik.Text);
            await faturaService.GetToken();
            var response = await
faturaService.GetRecipientDataByTaxIDOrTRID(taxId);
            if (response is GIBResponseModel)
            {
                RecipientModel recipient = response.data;
                var unvan = recipient.unvan;
                var adi = recipient.adi;
                var soyadi = recipient.soyadi;
                var vergiDairesi = recipient.vergiDairesi;
            }

Ahmet Bey :( bu kodları derleyemedim ama hata verdi
https://github.com/Orcunary/BFY.Fatura/blob/master/faturaOlustur/Form1.cs
button2_Click olayına bakabilir misiniz?

Önem Derecesi Kod Açıklama Proje Dosya Çizgi Gizleme Durumu
Hata CS0305 Genel tür 'GIBResponseModel<T>' kullanmak için 1 türü bağımsız
değişkenler gerekir


Orçun DİYARBAKIRLI



ahmetaksoy1985 ***@***.***>, 4 Haz 2023 Paz, 20:23 tarihinde
şunu yazdı:

**Comment by Orcunary** [comment]
Bir de
 var response = faturaService.CreateInvoiceAndGetHTML(nesne, false);


                using (var client = new WebClient())
                {

client.DownloadFile(faturaService.GetDownloadURL(response.Result.data,
false), "a.html");
                }

bu doğru bir kullanım olur mu ?
Orçun DİYARBAKIRLI



Orçun Diyarbakırlı ***@***.***>, 4 Haz 2023 Paz, 20:55
tarihinde şunu yazdı:

**Comment by ahmetaksoy1985** [comment]
Aşağıdaki gibi olacaktı. Düzeltmeyi unutmuşum. Konsol uygulamasında denemiştim.

`if(response is GIBResponseModel)
{

RecipientModel recipient = response.data;
unvan.Text = recipient.unvan;
adi.Text = recipient.adi;
soyadi.Text = recipient.soyadi;
vergidairesi.Text = recipient.vergiDairesi;
} `

**Comment by Orcunary** [comment]
if(response is GIBResponseModel)
GIBResponseModel  yine  t değişkeni istiyor derlemiyor

Orçun DİYARBAKIRLI



ahmetaksoy1985 ***@***.***>, 4 Haz 2023 Paz, 21:02 tarihinde
şunu yazdı:

**Comment by ahmetaksoy1985** [comment]
> Bir de var response = faturaService.CreateInvoiceAndGetHTML(nesne, false); using (var client = new WebClient()) { client.DownloadFile(faturaService.GetDownloadURL(response.Result.data, false), "a.html"); } bu doğru bir kullanım olur mu ? Orçun DİYARBAKIRLI Orçun Diyarbakırlı ***@***.***>, 4 Haz 2023 Paz, 20:55 tarihinde şunu yazdı:
> […](#)

Webclient sınıfı deprecated. Ben size kendi yazdığım kodları gönderirim.

**Comment by ahmetaksoy1985** [comment]
> if(response is GIBResponseModel) GIBResponseModel yine t değişkeni istiyor derlemiyor Orçun DİYARBAKIRLI ahmetaksoy1985 ***@***.***>, 4 Haz 2023 Paz, 21:02 tarihinde şunu yazdı:
> […](#)

Kodları güncelledim. Tekrar aldınız mı? Kodlar çalışıyor. Ben konsol uygulamasında denedim.

[https://github.com/ahmetaksoy1985/e-arsiv-fatura-dotnet](url)

**Comment by ahmetaksoy1985** [comment]
Birkaç gün beklerseniz sizin kodları düzenlerim. Çok güzel olur.

**Comment by Orcunary** [comment]
Tamam Ahmet bey,beklerim tabi çok teşekkür ederim.

4 Haz 2023 Pzr 22:24 tarihinde ahmetaksoy1985 ***@***.***>
şunu yazdı:

**Comment by ahmetaksoy1985** [comment]
> Bir de var response = faturaService.CreateInvoiceAndGetHTML(nesne, false); using (var client = new WebClient()) { client.DownloadFile(faturaService.GetDownloadURL(response.Result.data, false), "a.html"); } bu doğru bir kullanım olur mu ? Orçun DİYARBAKIRLI Orçun Diyarbakırlı ***@***.***>, 4 Haz 2023 Paz, 20:55 tarihinde şunu yazdı:
> […](#)

Şöyle bir fonksiyon yazmışım. 

faturaService.GetDownloadURL(response.Result.data,
false)`

Üstten gelen stringi uri olarak girip outputFolderPath kısmına da klasörü belirtirseniz. Zip dosyasını da açıp indirir.

public static async Task DownloadExtractZipFileAsync(string uri, string outputFolderPath)
       {
            if (!Uri.TryCreate(uri, UriKind.Absolute, out _))
                throw new InvalidOperationException("URI is invalid.");
            byte[] fileBytes = await httpClient.GetByteArrayAsync(uri);
            using (MemoryStream ms = new MemoryStream(fileBytes))
            using (var zip = new ZipArchive(ms, ZipArchiveMode.Read))
            {
                zip.ExtractToDirectory(outputFolderPath, true);
            }
        }

**Comment by ahmetaksoy1985** [comment]
Orçun Bey çok teşekkürler ederim helvalar için. Bayıldım. Ellerinize sağlık. 

Düzelttim. Prod olarak giriş yaparsanız firma bilgilerini çekiyor. SMS onaylama ve faturayı görüntüleme kısmını yapacağım. Login kısmını her click olayı yerine 1 kere yaparsanız daha iyi olur. Onun içinde ayrı Login Form'u yapmayı düşünüyorum. Tek bir form içinde olsun derseniz en üste login için button koyabiliriz. Bir de üstteki combobox’ları tam olarak nasıl kullanmak istiyorsunuz. Ben sql ile firma bilgilerini çekip combobox ile listeliyorum.

[https://github.com/ahmetaksoy1985/BFY.Fatura](url)

**Comment by Orcunary** [comment]
Ahmet Bey afiyet olsun :) Çok teşekkür ederim hocam bende henüz deneme fırsatı bulamadım login için bende o tarz bir form düşünmüştüm doğrusu. Combobox larda insanların ünvanları ve kullanıcı şifre bilgileri yer alacak, aynı form üzerinden comboxta seçili ünvan için yanş birden fazla ünvan ve şifre bilgisi ile fatura kesilebilecek.

**Comment by ahmetaksoy1985** [comment]
Şimdi anladım Orçun Bey 2 tane Combobox olmasını. Şöyle yapabiliriz. Login formunda kullanıcı bilgisi ve şifre girilirken otomatik login seçeneği seçilirse direk fatura kesme formu açılır her başlatmada. Logout buttonuna basınca tekrar login formu açılır. Login olduğunuzda ise firma bilgisini siteden çekip gösteririz.
